version: 2
jobs:
  build:
    docker:
      - image: quramy/opencvjs-emcc:sdk-tag-1.37.21-64bit

    working_directory: ~/repo

    steps:

      - checkout

      - run:
          name: get src
          command: |
            git clone https://github.com/opencv/opencv.git
            cd opencv
            git checkout 3.1.0
            cd ..

      - run:
          name: build wasm
          command: |
            python make.py --wasm

      - store_artifacts:
          path: build
          destination: wasm
